// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCayoK0GTSmt0m04iWcgUM9-UI3Fn6aGR0',
    appId: '1:73110842497:web:5aaf79549ef006c1ea7180',
    messagingSenderId: '73110842497',
    projectId: 'testing-app-4e1e1',
    authDomain: 'testing-app-4e1e1.firebaseapp.com',
    storageBucket: 'testing-app-4e1e1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwat7Ok_9xjvvm7BnZCfw4E76pSJPZmGo',
    appId: '1:73110842497:android:41961421acf9b056ea7180',
    messagingSenderId: '73110842497',
    projectId: 'testing-app-4e1e1',
    storageBucket: 'testing-app-4e1e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGEeQGn5tkobg9uHcdy71Hp7Jb5b67ozo',
    appId: '1:73110842497:ios:c66a4a58e8d4c381ea7180',
    messagingSenderId: '73110842497',
    projectId: 'testing-app-4e1e1',
    storageBucket: 'testing-app-4e1e1.appspot.com',
    iosClientId: '73110842497-9shd6in67gq2nl13d4cu9bj56gu5qvlp.apps.googleusercontent.com',
    iosBundleId: 'com.example.testingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGEeQGn5tkobg9uHcdy71Hp7Jb5b67ozo',
    appId: '1:73110842497:ios:c66a4a58e8d4c381ea7180',
    messagingSenderId: '73110842497',
    projectId: 'testing-app-4e1e1',
    storageBucket: 'testing-app-4e1e1.appspot.com',
    iosClientId: '73110842497-9shd6in67gq2nl13d4cu9bj56gu5qvlp.apps.googleusercontent.com',
    iosBundleId: 'com.example.testingApp',
  );
}
